apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: {{ .Values.php.replicaCount }}
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php-container
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          ports:
            - containerPort: 9000
