apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
spec:
  secretStoreRef:
    name: my-secret-store
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: rootPassword
      remoteRef:
        key: mysql-root-password
        version: AWSCURRENT
        property: rootPassword
